server:
  port: 8081
#logging:
#  level:
#    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        provider:
          my-client: # can be any name based on client details.
            #token-uri: https://host/auth/realms/../openid-connect/token
            token-uri: https://<token-host>/v2/oauth/token
        registration:
          my-client:
           client-id: ###CLIENT-ID###
           client-secret: ###CLIENT-SECRET###
           authorization-grant-type: client_credentials
           client-authentication-method: post

app:
  props:
    api-uri: https://some-uri/